---
- name: "Ensure data dir exists"
  ansible.builtin.file:
    path: "{{ data_dir }}"
    owner: "{{ username }}"
    state: directory
    mode: "774"

- name: "Set final geth config"
  ansible.builtin.set_fact:
    final_geth_config: "{{ default_geth_config | combine(geth_config, recursive=true) }}"

- name: "Copy Geth config in place"
  ansible.builtin.template:
    src: config.toml.j2
    dest: "{{ data_dir }}/config.toml"
    owner: "{{ username }}"
    mode: "644"
  when:
    - final_geth_config is defined
    - final_geth_config.keys() | length > 0
  notify: restart_service
