---
- name: "Dump geth config"
  ansible.builtin.shell: "{{ chain_bin }} dumpconfig > {{ chain_config_path }}"
  args:
    creates: "{{ chain_config_path }}"

- name: "Change ownership of config"
  ansible.builtin.file:
    path: "{{ chain_config_path }}"
    owner: "{{ username }}"

- name: "Update config variables" # noqa risky-file-permissions
  community.general.ini_file:
    path: "{{ chain_config_path }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - {section: Eth, option: SyncMode, value: "\"{{ geth_syncmode }}\""}

    - {section: Node, option: DataDir, value: "\"{{ geth_datadir }}\""}
    - {section: Node, option: HTTPHost, value: "\"{{ geth_http_addr }}\""}
    - {section: Node, option: HTTPPort, value: "{{ geth_http_port }}"}
    - {section: Node, option: HTTPVirtualHosts, value: "[\"{{ geth_http_vhosts | join('\", \"') }}\"]"}

    - {section: Metrics, option: HTTP, value: "\"{{ geth_metrics_addr }}\""}
    - {section: Metrics, option: Port, value: "{{ geth_metrics_port }}"}
    - {section: Metrics, option: Enabled, value: "{{ geth_metrics | string | lower }}"}
