---
- name: "Populate service facts"
  ansible.builtin.service_facts: {}

- name: "Stop service if exists"
  ansible.builtin.systemd:
    name: "{{ systemd_unit_name }}"
    state: stopped
  when: systemd_unit_name in ansible_facts.services

- name: "Install repository from PPA"
  ansible.builtin.apt_repository:
    repo: ppa:ethereum/ethereum
  when:
    - ansible_distribution == "Ubuntu"

- name: "Install apt package"
  ansible.builtin.apt:
    pkg: ethereum
    update_cache: true
  when:
    - ansible_distribution == "Ubuntu"

- name: "Create user {{ username }}"
  ansible.builtin.user:
    name: "{{ username }}"

- name: "Create geth config dir"
  ansible.builtin.file:
    dest: "{{ geth_config_dir }}"
    owner: "{{ username }}"
    state: directory
    mode: "744"
