---
- name: "Populate service facts"
  ansible.builtin.service_facts: {}

- name: "Stop service if exists"
  ansible.builtin.systemd:
    name: "{{ daemon_name }}"
    state: stopped
  when: daemon_name~'.service' in ansible_facts.services

- name: "Create user {{ username }}"
  ansible.builtin.user:
    name: "{{ username }}"

##
## Insall ethereum (geth) binary
##

- name: "Install repository from PPA"
  ansible.builtin.apt_repository:
    repo: ppa:ethereum/ethereum
  when:
    - ansible_distribution == "Ubuntu"

- name: "Install apt package"
  ansible.builtin.apt:
    pkg: ethereum
    update_cache: true
  when:
    - ansible_distribution == "Ubuntu"
