---
- name: "Create user {{ username }}"
  ansible.builtin.user:
    name: "{{ username }}"

- name: "Create systemd service file"
  ansible.builtin.template:
    src: templates/service.j2
    dest: "/etc/systemd/system/{{ daemon_name }}.service"
    mode: "644"

- name: "Install repository from PPA"
  ansible.builtin.apt_repository:
    repo: ppa:ethereum/ethereum
  when:
    - ansible_distribution == "Ubuntu"

- name: "Install apt package"
  ansible.builtin.apt:
    pkg: ethereum
    update_cache: true
  when:
    - ansible_distribution == "Ubuntu"

- name: "Create data dir"
  ansible.builtin.file:
    dest: "{{ chain_data_dir }}"
    owner: "{{ username }}"
    state: directory
    mode: "744"
