---
- name: Create systemd service file
  ansible.builtin.template:
    src: templates/service.j2
    dest: "/etc/systemd/system/{{ systemd_unit_name }}"
    mode: "644"

- name: Enable and start service
  ansible.builtin.systemd:
    name: "{{ systemd_unit_name }}"
    state: started
    daemon_reload: true
    enabled: true
