---
# <chain_name> defines the a cosmos-sdk based chain to init
chain_name: ""

# <chain_bin_flags> is an optinal extra bin flags
# e.g. chain_bin_flags: "--log_format json"

# <chain_data_dir> is the optional parametr for --home flag,
# by default equals node_home value from chain registry (e.g. $HOME/.osmosis)
# e.g. chain_data_dir: /mnt/data/.osmosis

# <chain_minimum_gas_prices> defines minimum transaction fee
# it is recommended to set this parameter
# to prevent getting spammed by transactions with no gas
# e.g. chain_minimum_gas_prices: 0.25token1;0.0001token2

# <chain_moniker> is the custom username of your node
chain_moniker: moniker-1

# <cosmovisor_daemon_home> is the location where the `cosmovisor/` dir is kept.
# Leave empty to initialize with value obtained from chain registry.
# e.g. cosmovisor_daemon_home: ""

# <cosmovisor_daemon_allow_download_binaries>, if `true`, will enable auto-downloading of new binaries
# (for security reasons, this is intended for full nodes rather than validators).
cosmovisor_daemon_allow_download_binaries: false

# <cosmovisor_daemon_restart_after_upgrade>, if `true`, restarts the subprocess with the same command-line
# arguments and flags (but with the new binary) after a successful upgrade.
cosmovisor_daemon_restart_after_upgrade: true

# <cosmovisor_daemon_poll_interval> is the interval length for polling the upgrade plan file.
# The value can either be a number (in milliseconds) or a duration (e.g. `1s`).
cosmovisor_daemon_poll_interval: 300

# <cosmovisor_unsafe_skip_backup>, if true, upgrades directly without performing a backup;
# otherwise backs up the data before trying the upgrade.
cosmovisor_unsafe_skip_backup: false

# <cosmovisor_daemon_preupgrade_max_retries> is the maximum number of times to call pre-upgrade
# in the application after exit status of 31. After the maximum number of retries, cosmovisor fails the upgrade.
cosmovisor_daemon_preupgrade_max_retries: 0

# <username> is the non-root user under which daemon will operate
username: cosmos

# <home_dir> is a user home dir
home_dir: "/home/{{ username }}"

# <chain_registry_url> is the URL to get cosmos-sdk based chain metadata.
chain_registry_url: https://raw.githubusercontent.com/cosmos/chain-registry/master/{{ chain_name }}/chain.json

# <binary_arch> is the binary system/architecture key to download
binary_arch: linux/amd64
