---
# <username> is the non-root user under which daemon will operate
username: cosmos

# <home_dir> is a user home dir
home_dir: "/home/{{ username }}"

# <bin_dir> is a binaries location dir, should be in the PATH.
bin_dir: /usr/local/bin

# <chain_registry_url> is the URL to get Cosmos-SDK based chain metadata.
# This value will almost never change.
chain_registry_url: https://raw.githubusercontent.com/cosmos/chain-registry/master/{{ chain_name }}/chain.json

# <binary_arch> is the system/architecture string to download chain binary.
binary_arch: linux/amd64

# <chain_name> defines the a Cosmos-SDK based chain to init
# Requred to be set in role vars.
chain_name: ""

# <chain_bin_flags> is an optinal extra bin flags
# e.g. chain_bin_flags: "--log_format json"

# <chain_data_dir> is the optional parametr for --home flag,
# by default equals node_home value from chain registry (e.g. $HOME/.osmosis)
# e.g. chain_data_dir: /mnt/data/.osmosis

# <chain_minimum_gas_prices> defines minimum transaction fee
# it is recommended to set this parameter
# to prevent getting spammed by transactions with no gas
# e.g. chain_minimum_gas_prices: 0.25token1;0.0001token2

# <chain_addrbook_url> is an optinal URL to download chain addrbook.json
# e.g. chain_addrbook_url: https://network.terra.dev/addrbook.json

# <chain_moniker> is the custom username of your node
chain_moniker: moniker-1

# <chain_specific_config> is the variable to control loading of chain specific task
# to update the chain config. Set in chain vars.
chain_specific_config: false

# <chain_state_pruning> defines the pruning strategy.
# Avaiable options are default, nothing, everything, custom.
chain_pruning: default

# <chain_pruning_keep_recent> defines number of last states to keep (e.g. 100).
# Only applied when chain_pruning is custom.
chain_pruning_keep_recent: "0"

# <chain_pruning_keep_every> defines each Nth state to keep (e.g. 500).
# Only applied when chain_pruning is custom.
chain_pruning_keep_every: "0"

# <chain_pruning_interval> defines the prunning interval (e.g. 10)
# Only applied when chain_pruning is custom.
chain_pruning_interval: "0"

# <cosmovisor_daemon_home> is the location where the `cosmovisor/` dir is kept.
# Leave empty to initialize with value obtained from chain registry.
# e.g. cosmovisor_daemon_home: ""

# <cosmovisor_daemon_allow_download_binaries>, if `true`, will enable auto-downloading of new binaries
# (for security reasons, this is intended for full nodes rather than validators).
cosmovisor_daemon_allow_download_binaries: false

# <cosmovisor_daemon_restart_after_upgrade>, if `true`, restarts the subprocess with the same command-line
# arguments and flags (but with the new binary) after a successful upgrade.
cosmovisor_daemon_restart_after_upgrade: true

# <cosmovisor_daemon_poll_interval> is the interval length for polling the upgrade plan file.
# The value can either be a number (in milliseconds) or a duration (e.g. `1s`).
cosmovisor_daemon_poll_interval: 300

# <cosmovisor_unsafe_skip_backup>, if true, upgrades directly without performing a backup;
# otherwise backs up the data before trying the upgrade.
cosmovisor_unsafe_skip_backup: true

# <cosmovisor_daemon_preupgrade_max_retries> is the maximum number of times to call pre-upgrade
# in the application after exit status of 31. After the maximum number of retries, cosmovisor fails the upgrade.
cosmovisor_daemon_preupgrade_max_retries: 0

# <cosmovisor_version> to install. Chains that use Cosmos-SDK `v0.44.3`
# or earlier and want to use auto-download feature MUST use Cosmovisor `v0.1.0`
cosmovisor_version: latest

# <cosmovisor_daemon_description> sets SystemD unit description.
cosmovisor_daemon_description: Cosmovisor Daemon

# quicksync_available defines whether quicksync mode is avaialble for chain.
# Set in chain vars.
quicksync_available: false

# <quicksync_mode> defines the chain data file to download.
# Avaialable values are pruned, default, archive and none (sync from beginning).
quicksync_mode: pruned

# <quicksync_mirror> selects the regional mirror.
# Avaiable options are Netherlands, Singapore, SanFrancisco
quicksync_mirror: Netherlands

# <quicksync_force> forces the chain data download step.
# Warning, the content of the data dir will be wiped.
# By default chain data will be downloaded only after chain init.
quicksync_force: false

# <quicksync_donwload_dir> is the temporary dir to keep downloaded file.
# The aria2c package is utilized to speed up download process,
# but it requires double size to first download and then unpack data archive.
# In cloud environment the download dir often points to temporary mounted drive.
quicksync_donwload_dir: /tmp/quicksync
