---
chain_minimum_gas_prices: "0.001uosmo"
chain_addrbook_url: https://quicksync.io/addrbook.osmosis.json
quicksync_available: true
make_command: >
  wget https://github.com/CosmWasm/wasmvm/releases/download/v1.0.0-beta7/libwasmvm_muslc.a -O /lib/libwasmvm_muslc.a &&
  BUILD_TAGS=muslc make build &&
  cp ./build/osmosisd {{ bin_dir }}
