---
dependency:
  name: galaxy
driver:
  name: ec2
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: instance
    image: ${MOLECULE_IMAGE_DEBIAN}
    image_owner: aws-marketplace
    instance_type: c5.2xlarge
    vpc_subnet_id: ${MOLECULE_VPC_SUBNET_ID}
    boot_wait_seconds: 10
    volumes:
      - device_name: xvda
        ebs:
          volume_size: 40
          delete_on_termination: true
    tags:
      Name: molecule-blockbook-${BLOCKBOOK_CHAIN_NAME}
provisioner:
  name: ansible
verifier:
  name: testinfra
scenario:
  name: blockbook
  create_sequence:
    - create
    - prepare
  check_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
