---
- name: "Set chain configs"
  set_fact:
    chain_config_path: "{{ chain_data_dir }}/config/config.toml"
    chain_config_app_path: "{{ chain_data_dir }}/config/app.toml"

# config.toml

- name: "Update persistent peers" # noqa risky-file-permissions
  community.general.ini_file:
    path: "{{ chain_config_path }}"
    section: "p2p"
    option: "persistent_peers"
    value: "\"{{ chain_peers }}\""

- name: "Update indexer" # noqa risky-file-permissions
  community.general.ini_file:
    path: "{{ chain_config_path }}"
    section: "tx_index"
    option: "indexer"
    value: "\"kv\""
  when: chain_pruning != 'everything'

- name: "Update indexer (if pruning is everyting)" # noqa risky-file-permissions
  community.general.ini_file:
    path: "{{ chain_config_path }}"
    section: "tx_index"
    option: "indexer"
    value: "\"null\""
  when: chain_pruning == 'everything'

# app.toml

- name: "Update minimum gas price" # noqa risky-file-permissions
  community.general.ini_file:
    path: "{{ chain_config_app_path }}"
    section: ""
    option: "minimum-gas-prices"
    value: "\"{{ chain_minimum_gas_prices }}\""

- name: "Update pruning strategy" # noqa risky-file-permissions
  community.general.ini_file:
    path: "{{ chain_config_app_path }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - {section: "", option: pruning, value: "\"{{ chain_pruning }}\""}
    - {section: "", option: pruning-keep-recent, value: "\"{{ chain_pruning_keep_recent }}\""}
    - {section: "", option: pruning-keep-every, value: "\"{{ chain_pruning_keep_every }}\""}
    - {section: "", option: pruning-interval, value: "\"{{ chain_pruning_interval }}\""}

- name: "Enable API server" # noqa risky-file-permissions
  community.general.ini_file:
    path: "{{ chain_config_app_path }}"
    section: "api"
    option: "enable"
    value: "{{ chain_api_enable | string | lower }}"


- name: "Include chain tasks only if such exist, otherwise skip the task"
  include_tasks:
    file: "{{ item }}"
  with_first_found:
    files:
     - "config_{{ chain_name }}.yml"
    skip: true
