---
- name: "Create user {{ username }}"
  ansible.builtin.user:
    name: "{{ username }}"

- name: "Create systemd service file"
  ansible.builtin.template:
    src: templates/service.j2
    dest: "/etc/systemd/system/{{ cosmovisor_daemon_name }}.service"
    mode: "644"

- name: "Install chain binary"
  block:

    - name: "Unarchive chain binary"
      ansible.builtin.unarchive:
        src: "{{ chain_bin_url }}"
        dest: "{{ bin_dir }}"
        mode: "755"
        remote_src: true
      when: chain_bin_url is match('\.tar\.gz$') # .tar.gz

    - name: "Download chain binary"
      ansible.builtin.get_url:
        url: "{{ chain_bin_url }}"
        dest: "{{ bin_dir }}"
        mode: "755"
      register: get_chain_bin_result
      when: not chain_bin_url is match('\/[^.]+$') # no extension

    - name: "Link download chain binary"
      ansible.builtin.file:
        src: "{{ get_chain_bin_result.dest }}"
        dest: "{{ bin_dir }}/{{ chain_bin }}"
        state: link
      when: not chain_bin_url is match('\/[^.]+$') # no extension

  when: chain_bin_url is defined

- name: "Ensure permissions of data dir"
  ansible.builtin.file:
    dest: "{{ chain_data_dir }}"
    state: directory
    owner: "{{ username }}"
    mode: "774"

- name: "Install cosmovisor"
  ansible.builtin.command: "go install github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor@{{ cosmovisor_version }}"
  args:
    creates: "{{ bin_dir }}/cosmovisor"
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
    GOBIN: "{{ bin_dir }}"

- name: "Create cosmovisor folders"
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: "{{ username }}"
    state: directory
    mode: "744"
  loop:
    - "{{ cosmovisor_daemon_home }}/cosmovisor/genesis/bin"
    - "{{ cosmovisor_daemon_home }}/cosmovisor/upgrades"

- name: "Copy chain binary to cosmovisor home dir"
  ansible.builtin.copy:
    remote_src: true
    src: "{{ bin_dir }}/{{ chain_bin }}"
    dest: "{{ cosmovisor_daemon_home }}/cosmovisor/genesis/bin/{{ chain_bin }}"
    owner: "{{ username }}"
    mode: preserve
