---
- name: "Include {{ chain_name }} vars"
  include_vars:
    file: "vars/{{ chain_name }}.yml"

- name: "Get metadata from chain registry"
  ansible.builtin.uri:
    url: "{{ chain_registry_url }}"
    return_content: true
    status_code:
      - 200
  register: metadata

- name: "Set role facts"
  set_fact:
    chain_bin_flags: "{{ chain_bin_flags | default('') }}"
    chain_bin_url: "{{ chain_bin_url | default(metadata.json.codebase.binaries[binary_arch]) }}"
    chain_bin: "{{ metadata.json.daemon_name }}"
    chain_data_dir: "{{ chain_data_dir | default(metadata.json.node_home | replace('$HOME', home_dir) ) }}"
    chain_genesis_url: "{{ metadata.json.genesis.genesis_url }}"
    chain_id: "{{ metadata.json.chain_id }}"
    chain_peers: "{{ metadata.json.peers.persistent_peers | trustwallet.blockchains.to_cosmos_peers }}"
    cosmovisor_daemon_name: "{{ metadata.json.daemon_name }}"
    cosmovisor_daemon_home: "{{ cosmovisor_daemon_home | default(metadata.json.node_home | replace('$HOME', home_dir) ) }}"
