---
- name: "Include {{ chain_name }} vars"
  include_vars:
    file: "vars/{{ chain_name }}.yml"

- name: "Get metadata from chain registry"
  ansible.builtin.uri:
    url: "{{ chain_registry_url }}"
    return_content: true
    status_code:
      - 200
  register: metadata

# - name: "Print chain metadata"
#   debug:
#     var: metadata.json

- name: "Set role facts"
  set_fact:
    chain_bin_flags: "{{ chain_bin_flags | default('') }}"
    chain_data_dir: "{{ chain_data_dir | default(metadata.json.node_home) }}"
    chain_bin_url: "{{ metadata.json.codebase.binaries[binary_arch] }}"
    chain_genesis_url: "{{ metadata.json.genesis.genesis_url }}"
    chain_peers: "{{ metadata.json.peers.persistent_peers | to_cosmos_peers }}"
    cosmovisor_daemon_name: "{{ metadata.json.daemon_name }}"
    cosmovisor_daemon_home: "{{ cosmovisor_daemon_home | default(metadata.json.node_home) }}"
    cosmovisor_daemon_description: "{{ metadata.json.pretty_name }} (cosmos-sdk) Chain Daemon"
