---
- include_tasks: load_vars.yml

- include_tasks: install.yml

- include_tasks: init.yml

- include_tasks: config.yml

- include_tasks: sync.yml
  when:
    - init_result.changed or quicksync_force
    - quicksync_available
    - quicksync_mode != 'none'
