---
- name: "Create systemd service file"
  ansible.builtin.template:
    src: templates/service.j2
    dest: "/etc/systemd/system/{{ daemon_name }}.service"
    mode: "644"

- name: "Enable and start service"
  ansible.builtin.systemd:
    name: "{{ daemon_name }}"
    state: started
    daemon_reload: true
    enabled: true
