---
- name: Converge
  hosts: all
  tasks:
    - name: "Include roles/ethereum"
      ansible.builtin.include_role:
        name: roles/ethereum
      vars:
        ansible_become: true
        geth_config:
          Eth:
            SyncMode: light

