---
- name: Converge
  hosts: all
  tasks:
    - name: "Include roles/cosmos"
      ansible.builtin.include_role:
        name: roles/cosmos
      vars:
        ansible_become: true
        chain_name: "{{ lookup('env', 'COSMOS_CHAIN_NAME') }}"
        chain_git_repo: https://github.com/osmosis-labs/osmosis
        chain_version: v7.2.0
        quicksync_mode: none
