---
- name: Converge
  hosts: all
  tasks:
    - name: "Include roles/cosmos"
      include_role:
        name: "roles/cosmos"
      vars:
        ansible_become: true
        chain_name: "{{ lookup('env', 'COSMOS_CHAIN_NAME') }}"
        # chain_data_dir: /mnt/data/.osmosisd
        # chain_bin_url: https://github.com/osmosis-labs/osmosis/releases/download/v6.1.0/osmosisd-6.1.0-linux-amd64
        # quicksync_force: true
        quicksync_mode: none
