---
dependency:
  name: galaxy
driver:
  name: ec2
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: ami-0fd19782996d81f2d
    instance_type: t3.medium
    vpc_subnet_id: ${VPC_SUBNET_ID}
    volumes:
      - device_name: /dev/sdf
        ebs:
          volume_size: 40 
          delete_on_termination: true
    tags:
      Name: molecule-cosmos
provisioner:
  name: ansible
verifier:
  name: testinfra
scenario:
  name: cosmos
  create_sequence:
    - create
    - prepare
  check_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - prepare
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
