---
- name: Converge
  hosts: all
  tasks:
    - name: "Include roles/near"
      ansible.builtin.include_role:
        name: roles/near
      vars:
        ansible_become: true
        quicksync_mode: none
