---
##
## ETHEREUM OPTIONS
##

geth_datadir: "{{ chain_data_dir }}"
# full: Downloads all blocks (including headers, transactions, and receipts) and generates the state of the blockchain incrementally by executing every block.
# fast: Downloads all blocks (including headers, transactions and receipts), verifies all headers, and downloads the state and verifies it against the headers.
# snap: Same functionality as fast, but with a faster algorithm.
# light: Downloads all block headers, block data, and verifies some randomly.
geth_syncmode: snap

##
## API AND CONSOLE OPTIONS
##

geth_http: true
geth_http_addr: 0.0.0.0
geth_http_port: 8545
geth_http_api: eth,net,web3
geth_http_vhosts: "*"

##
## METRICS AND STATS OPTIONS
##

geth_metrics: true
geth_metrics_addr: 0.0.0.0
geth_metrics_port: 6060
