---
name: Ansible Galaxy

on:
  push:
    branches: [ main ]
    paths: [ "galaxy.yml" ]

jobs:
  ansible-galaxy:
    name: "ansible-galaxy"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
      - run: "pip install ansible"
      - run: "ansible-galaxy collection build"
      - run: "ansible-galaxy collection publish --api-key ${{ secrets.GALAXY_API_KEY }} trustwallet-blockchains-*.tar.gz"
