---
name: Ansible Galaxy

on:
  push:
    branches:
      - main
    paths:
      - galaxy.yml

jobs:
  ansible-galaxy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install Ansible package
        run: pip install ansible
      
      - name: Build Ansible Galaxy collection
        id: build
        run: |
          VERSION=$(ansible-galaxy collection build | sed 's/.*-\(.*\)\.tar\.gz/\1/')
          echo "::set-output name=collection-version::$VERSION"
      
      - name: Publish Ansible Galaxy collection
        run: ansible-galaxy collection publish --api-key ${{ secrets.GALAXY_API_KEY }} trustwallet-blockchain-*.tar.gz
