---
name: Linter

on:
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    name: "ansible-lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
      - run: "pip install ansible ansible-lint boto3"
      - run: "ansible-lint ."
  yamllint:
    name: "yamllint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
      - run: "pip install yamllint"
      - run: "yamllint -s ."
