---
name: Test Ethereum role

on:
  pull_request:
    branches:
      - main
    paths:
      - roles/ethereum/**
      - molecule/ethereum/**

jobs:
  ansible-galaxy:
    name: "ansible-galaxy"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      
      - name: Confiugre AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - uses: actions/setup-python@v2
      - run: pip install -r molecule/requirements.txt

      - name: Test role with Molecule
        if: github.repository_owner == 'trustwallet'
        run: molecule -v test -s ethereum
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          MOLECULE_VPC_SUBNET_ID: ${{ secrets.MOLECULE_VPC_SUBNET_ID }}
          MOLECULE_IMAGE: ${{ secrets.MOLECULE_IMAGE }}
