---
name: Test Cosmos role (osmosis)

on:
  pull_request:
    branches:
      - main
    paths:
      - roles/cosmos/**
      - molecule/cosmos/**

permissions:
  id-token: write
  contents: read

env:
  MOLECULE_SCENARIO: cosmos

jobs:
  ansible-galaxy:
    name: "ansible-galaxy"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Confiugre AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r molecule/requirements.txt
        if: steps.cache.outputs.cache-hit != 'true'

      # cosmos role is using the collection plugin
      - run: ansible-galaxy collection build
      - run: find trustwallet-blockchain-* | xargs ansible-galaxy collection install

      - name: Test role with Molecule
        if: github.repository_owner == 'trustwallet'
        run: molecule -v test -s $MOLECULE_SCENARIO
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          MOLECULE_VPC_SUBNET_ID: ${{ secrets.MOLECULE_VPC_SUBNET_ID }}
          MOLECULE_IMAGE: ${{ secrets.MOLECULE_IMAGE }}
          COSMOS_CHAIN_NAME: osmosis
